services:
    beexample-app:
        build:
            context: .
            dockerfile: Dockerfile

        ports:
            - "3019:3000"
        restart: always
        env_file:
            - .env
        volumes:
            - ./data/app/uploads:/app/uploads
        depends_on:
            beexample-db:
                condition: service_healthy
        networks:
            - beexample-network

    beexample-db:
        image: postgres:16-alpine
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        restart: always
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}",
                ]
            interval: 5s
            timeout: 5s
            retries: 5
        networks:
            - beexample-network

networks:
    beexample-network:
