import { PostType } from "@prisma/client";
import {
    Award,
    BookOpen,
    Flame,
    MessageSquare,
    Heart,
    Megaphone,
    Ghost,
    Laugh,
    FileText,
    Volume2,
    Search,
    Calendar,
    Users,
    AlertTriangle,
    Lightbulb,
    Sparkles,
    MoreHorizontal,
} from "lucide-react";

export const POST_TYPE_ICONS: Record<PostType, React.ElementType> = {
    [PostType.MOTIVATIONAL]: Flame,
    [PostType.ACHIEVEMENT]: Award,
    [PostType.CONFESSION]: MessageSquare,
    [PostType.RANT]: AlertTriangle,
    [PostType.QUESTION]: BookOpen,
    [PostType.COMPLIMENT]: Heart,
    [PostType.SECRET_CRUSH]: Ghost,
    [PostType.MEME]: Laugh,
    [PostType.STORY]: FileText,
    [PostType.SHOUTOUT]: Megaphone,
    [PostType.LOST_FOUND]: Search,
    [PostType.EVENT_PROMO]: Calendar,
    [PostType.ROOMMATE_REQUEST]: Users,
    [PostType.COMPLAINT]: AlertTriangle,
    [PostType.ADVICE]: Lightbulb,
    [PostType.OTHER]: MoreHorizontal,
};
