name: Deploy to Hetzner VPS

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy:
        uses: mishodzuliashvili/hetzner-deploy-workflow/.github/workflows/deploy.yml@main
        secrets: inherit
