name: Deploy to Hetzner VPS

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install SSH client
              run: sudo apt-get install openssh-client

            - name: Set up SSH key
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
              run: |
                  mkdir -p ~/.ssh
                  echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts

            - name: Deploy to Hetzner VPS
              env:
                  HOST: ${{ secrets.HOST }}
                  USER: ${{ secrets.USER }}
                  PASSWORD: ${{ secrets.PASSWORD }}
              run: |
                  ssh $USER@$HOST << EOF
                    cd ~/beexample
                    git pull
                    echo "$PASSWORD" | sudo -S docker compose build
                    sudo docker compose up -d --remove-orphans
                    sudo docker builder prune -f
                    sudo docker image prune -f
                  EOF